# Generated by Django 5.1.15 on 2026-04-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.TextField(verbose_name='localisation'),
        ),
    ]
