# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[('client', 'Client'), ('admin', 'Administrateur')],
                default='client',
                max_length=16,
            ),
        ),
    ]
