# Generated by Django 5.1.15 on 2026-04-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shopproduct_highlights_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='highlights',
            field=models.TextField(blank=True, default='', help_text='Optionnel : une ligne = une puce à côté de la galerie.', verbose_name='puces (une ligne = une puce)'),
        ),
    ]
